services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - "3003:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_KEY=base64:secret
      - APP_URL=http://10.0.0.127:3003
      - SPEEDTEST_SCHEDULE=0 * * * *
    volumes:
      - /home/dhruv/homelab/speedtest-tracker:/config:Z
